---
title: '[Result] High-throughput Part Characterization (Colony scan)'
author: "Seong-Kun Bak (tjdrns227@gmail.com)"
date: '2022 8 25 '
output:
  html_document:
    df_print: paged
  pdf_document:
    latex_engine: xelatex
header-includes:
- \usepackage{fontspec}
- \setmainfont{NanumGothic}
---

```{r, setup, echo=FALSE}
knitr::opts_chunk$set(echo=FALSE, eval = FALSE, tidy=TRUE)
```

# High-throughput Part characterization

Doi : <https://doi.org/10.4014/jmb.2207.07013>

`Method II, Extra II` 를 토대로 Colony에서 Phenotype, Genotype을 획득하는 과정을 실제 코드로 재현하였습니다.

-   컴퓨터 분석은 Docker container를 사용하여 `tjdrns27/ont:2.4` 에서 진행되었습니다.

# Phenotyping

1.  Library 제작 및 Transformation

|                  |       |             |
|------------------|-------|-------------|
|                  | MW    | Volume (uL) |
| Promoter (1-23)  | 100   | 1.12        |
| RBS (C30)        | 100   | 1.12        |
| Terminator (P56) | 100   | 1.12        |
| pRSFduet_sfGFP   | 96.05 | 1.17        |
| pACBB_4-3_RFP    | 9.87  | 8.51        |
| DW               |       | 2.96        |

2.  Tag dispense (OT2)

```{=html}
<!-- -->
```
    Colony 수 : 240개
    Tag 수 : [A-E] [1-8] (40조합)
    Barcode : 6개

    Sequence Data = "/NGS/02_ont/2021/210701_DH5a-PLib/dh5a-plib/20210701_0930_MC-110372_0_agw324_ac3da2d2/fastq_pass"

> OT2 - `script/tagging_primer.py` 를 사용하여 96 well plate에 Tag Primer 와 PCR premix 분주
>
> 또는 손으로 직접 분주

3.  Colony Phenotype 분석

    > `Method II`의 방법에 따라 이미지 촬영
    >
    > `OpenCFU` 를 활용하여 콜로니 정보 Excel 파일 획득 및 Indexing
    >
    > 위에서 획득한 Index에 따라 Colony를 Tag primer가 분주된 96 well plate 로 접종 (PCR)

# Genotyping

1.  위 `Phenotyping` 에서 제작한 PCR product Pooling.
2.  Sequencing (`ONT with Zephyr` 참고)
3.  Sequence Analysis

### 1. Pre-processing

`Method I` 의 Pre-processing method에 따라 진행

```{bash, NanoFilt & Porechop}
# cd to Data path (fastq_pass)
barcodes=$(ls | grep 'barcode')

# Make analysis folder
for i in $barcodes; do mkdir ./"$i"/single_read; done

# Run NanoFilt
for i in $barcodes; do gunzip -c ./"$i"/*.fastq.gz | NanoFilt -q 7 -l 600 --maxlength 1500 | porechop --format fastq | gzip > ./"$i"/single_read/"$i".fastq.gz; done
```

### 2. Tag_demultiplex

```{bash}
python /script/ont_tag.py -i {} -r {} -o {$output}
```

### 3. Single-molecule analysis

1.  `/script/DB.py` 이용해서 reference DB 생성

```{=html}
<!-- -->
```
    ex)

    >P1_R21_sfGFP_T25
    ATGACGTC

```{bash}
for i in $barcodes; do for j in $(ls $barcodes | grep "*.fastq"); do minimap2 -ax map-ont -N 50 {$reference} "$j" | samtools view -bS -F 0x4 -F 0x900 | awk {"print $3"} | sort | uniq -c > "$j.txt" done done
```

### 4. Tag Result Analysis (Python)

Tag 분리 결과를 모아 `Score1`, `Score2`를 계산하여 최종 서열을 결정합니다.

최종적으로 phenotype 데이터와 genotype 데이터를 연결하여 Tag별 서열을 결정합니다.
